// <auto-generated />
namespace BA_Portal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class OtherDescription_Subjects : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OtherDescription_Subjects));
        
        string IMigrationMetadata.Id
        {
            get { return "201709021800245_OtherDescription_Subjects"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
